### Model
model_name_or_path: Qwen/Qwen2.5-Omni-7B
trust_remote_code: true

### Method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### Dataset
dataset: malaysian_asr
template: qwen2_omni  # Use Qwen2-Omni template for audio support
cutoff_len: 2048
max_samples: 100000  # Commented out - use full 5.2M dataset
overwrite_cache: false  # Reuse cache between runs (only rebuild if data/template changes)
preprocessing_num_workers: 1  # Use 1 worker for audio files to avoid multiprocessing issues

### Output
output_dir: outputs/qwen25omni-malaysian-asr-qlora
logging_steps: 10
save_steps: 500  # More frequent checkpoints for safety
eval_steps: 500  # Must match save_steps for load_best_model_at_end
plot_loss: true
overwrite_output_dir: false

### Train
per_device_train_batch_size: 16  # Increased to utilize A100-80GB (40-45GB usage)
gradient_accumulation_steps: 8   # Reduced while maintaining effective batch=128
learning_rate: 2.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 100
bf16: true
ddp_timeout: 180000000

### Eval
val_size: 0.1
per_device_eval_batch_size: 8  # Increased for faster evaluation
eval_strategy: steps
load_best_model_at_end: true

### LoRA
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05

### Quantization (QLoRA - 4-bit)
quantization_bit: 4
quantization_type: nf4
double_quantization: true

### Hardware optimization
flash_attn: auto
gradient_checkpointing: true

### Logging
report_to: none  # Disable to avoid JSON serialization issues with Qwen2.5-Omni config
logging_dir: outputs/qwen25omni-malaysian-asr-qlora/logs

