### Model
model_name_or_path: Qwen/Qwen2.5-Omni-7B
trust_remote_code: true

### Method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### Dataset
dataset: malaysian_asr
template: qwen2_omni  # Use Qwen2-Omni template for audio support
cutoff_len: 2048
max_samples: 10000  # ✅ START SMALL! Was 100000 - test with 10K first
overwrite_cache: true  # ✅ REBUILD CACHE with new prompt!
preprocessing_num_workers: 1

### Output
output_dir: outputs/qwen25omni-malaysian-asr-qlora-v2-conservative
logging_steps: 10
save_steps: 100        # ✅ MORE FREQUENT! Was 500 - catch early overfitting
eval_steps: 100        # ✅ MORE FREQUENT! Was 500 - evaluate often
plot_loss: true
overwrite_output_dir: false

### Train
per_device_train_batch_size: 4   # ✅ REDUCED! Was 16 - smaller batches
gradient_accumulation_steps: 8   # Effective batch = 32 (was 128)
learning_rate: 5.0e-5            # ✅ MUCH LOWER! Was 2.0e-4 - conservative
num_train_epochs: 0.5            # ✅ HALF EPOCH! Was 1.0 - stop early
lr_scheduler_type: cosine
warmup_steps: 50                 # ✅ REDUCED! Was 100
bf16: true
ddp_timeout: 180000000

### Eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
load_best_model_at_end: true

### LoRA (CONSERVATIVE CONFIG!)
lora_rank: 8          # ✅ REDUCED! Was 16 - fewer trainable params
lora_alpha: 16        # ✅ REDUCED! Was 32 - gentler updates
lora_dropout: 0.1     # ✅ INCREASED! Was 0.05 - more regularization

### Quantization (QLoRA - 4-bit)
quantization_bit: 4
quantization_type: nf4
double_quantization: true

### Hardware optimization
flash_attn: auto
gradient_checkpointing: true

### Logging
report_to: none  # Disable to avoid JSON serialization issues
logging_dir: outputs/qwen25omni-malaysian-asr-qlora-v2-conservative/logs


